"""Add research question to studies

Revision ID: fd736d82d7c8
Revises: caa979f28b4a
Create Date: 2026-09-18 13:56:40.594025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd736d82d7c8'
down_revision: Union[str, Sequence[str], None] = 'caa979f28b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('research_question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'research_question')
    # ### end Alembic commands ###
